name: Build and test on PR

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        swift: ["5.3"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: fwal/setup-swift@d43a564349d1341cd990cfbd70d94d63b8899475
        with:
          swift-version: ${{ matrix.swift }}

      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install tests output beautifier
        run: brew install xcbeautify

      - name: Build and test
        run: |
          xcodebuild test \
          -project UP\ Sample.xcodeproj \
          -scheme UP\ Sample \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.5' 
          | xcbeautify
